import {Engine} from '@babylonjs/core/Engines/engine.js';
import {Scene} from '@babylonjs/core/scene.js';
import {ArcRotateCamera} from '@babylonjs/core/Cameras/arcRotateCamera.js';
import {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight.js';
import {DirectionalLight} from '@babylonjs/core/Lights/directionalLight.js';
import {Vector3} from '@babylonjs/core/Maths/math.vector.js';
import {Color3,Color4} from '@babylonjs/core/Maths/math.color.js';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';
import {FarmChunk} from '../farming/FarmChunk.js';
const engine=new Engine(document.getElementById('tree'),true),scene=new Scene(engine);
scene.clearColor=new Color4(.75,.9,.94,1);
const camera=new ArcRotateCamera('camera',-Math.PI/2-.45,1.23,8.6,new Vector3(0,2.05,0),scene);camera.attachControl(engine.getRenderingCanvas(),true);camera.lowerRadiusLimit=5;camera.upperRadiusLimit=13;
const ambient=new HemisphericLight('sky',new Vector3(0,1,0),scene);ambient.intensity=.8;ambient.groundColor=new Color3(.35,.4,.25);
const sun=new DirectionalLight('sun',new Vector3(-.5,-1,.4),scene);sun.intensity=.9;
const chunk=new FarmChunk(scene,{id:'farm_000001',x:0,z:0});chunk.showDetail();const tree=chunk.appleTree;tree.setParent(null);tree.position.set(0,0,0);chunk.root.dispose();
const ground=MeshBuilder.CreateGround('grass',{width:200,height:200},scene);const grass=new StandardMaterial('grass',scene);grass.diffuseColor=Color3.FromHexString('#a4bd75');grass.specularColor=Color3.Black();ground.material=grass;
const shade=MeshBuilder.CreateDisc('shade',{radius:1.5,tessellation:48},scene);shade.rotation.x=Math.PI/2;shade.position.set(.25,.015,.12);const sm=new StandardMaterial('soft-shadow',scene);sm.diffuseColor=Color3.FromHexString('#677c46');sm.alpha=.24;shade.material=sm;
let visible=true;document.getElementById('harvest').onclick=()=>{visible=!visible;for(const fruit of chunk.appleFruits)fruit.setEnabled(visible);document.getElementById('harvest').textContent=visible?'Thu hoạch thử':'Hiện quả chín';};
engine.runRenderLoop(()=>scene.render());window.addEventListener('resize',()=>engine.resize());
