import { Engine } from '@babylonjs/core/Engines/engine.js';
import { Scene } from '@babylonjs/core/scene.js';
import { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera.js';
import { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight.js';
import { DirectionalLight } from '@babylonjs/core/Lights/directionalLight.js';
import { Vector3 } from '@babylonjs/core/Maths/math.vector.js';
import { Color4 } from '@babylonjs/core/Maths/math.color.js';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder.js';
import { createToyMaterial } from '../rendering/PlayTogetherTheme.js';
import { createToyFountain } from '../world/landmarks/createToyFountain.js';
const canvas = document.querySelector('#scene');
const engine = new Engine(canvas, true);
engine.maxFPS = 30;
engine.renderEvenInBackground = false;
const scene = new Scene(engine);
scene.clearColor = new Color4(0.76, 0.87, 0.93, 1);
const camera = new ArcRotateCamera('camera', Math.PI / 2 - 0.35, 1.02, 29, new Vector3(0, 2, 0), scene);
camera.attachControl(canvas, true); camera.lowerRadiusLimit = 14; camera.upperRadiusLimit = 45;
const sky = new HemisphericLight('sky', new Vector3(0, 1, 0), scene); sky.intensity = 0.65;
const sun = new DirectionalLight('sun', new Vector3(-0.4, -1, -0.5), scene); sun.intensity = 0.35;
const ground = MeshBuilder.CreateGround('plaza', { width: 120, height: 120 }, scene);
ground.material = createToyMaterial(scene, 'preview-ground', '#ddcfb7'); ground.position.y = -0.02;
createToyFountain(scene, null, null);
engine.runRenderLoop(() => { if (!document.hidden) scene.render(); });
window.addEventListener('resize', () => engine.resize());
