import {Engine} from '@babylonjs/core/Engines/engine.js';
import {Scene} from '@babylonjs/core/scene.js';
import {ArcRotateCamera} from '@babylonjs/core/Cameras/arcRotateCamera.js';
import {Vector3} from '@babylonjs/core/Maths/math.vector.js';
import {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight.js';
import {Color3,Color4} from '@babylonjs/core/Maths/math.color.js';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';
import {SeasonDecorations} from '../world/SeasonDecorations.js';
const engine=new Engine(document.querySelector('#scene'),true),scene=new Scene(engine);
scene.clearColor=new Color4(.12,.19,.28,1);
const overview=new URLSearchParams(location.search).has('plaza');
const camera=new ArcRotateCamera('camera',-2.28,overview ? .55 : 1.12,overview?70:11,overview?new Vector3(0,1,0):new Vector3(23,2.3,20),scene);camera.attachControl(engine.getRenderingCanvas(),true);
new HemisphericLight('sky',new Vector3(0,1,0),scene).intensity=1.1;
const ground=MeshBuilder.CreateGround('ground',{width:overview?120:80,height:overview?120:80},scene);ground.position.set(overview?0:23,0,overview?0:20);const mat=new StandardMaterial('grass',scene);mat.diffuseColor=new Color3(.3,.46,.22);ground.material=mat;
const position=()=>overview?{x:0,z:0}:{x:23,z:20};
let decor=new SeasonDecorations(scene,position,{mobile:true});decor.limit=overview?12:1;
document.querySelector('#toggle').onclick=()=>{if(decor){decor.dispose();decor=null;}else{decor=new SeasonDecorations(scene,position,{mobile:true});decor.limit=overview?12:1;}document.querySelector('#toggle').textContent=decor?'Tắt Halloween':'Bật Halloween';};
engine.runRenderLoop(()=>scene.render());window.addEventListener('resize',()=>engine.resize());
