import { Engine } from '@babylonjs/core/Engines/engine.js';
import { Scene } from '@babylonjs/core/scene.js';
import { ArcRotateCamera } from '@babylonjs/core/Cameras/arcRotateCamera.js';
import { DirectionalLight } from '@babylonjs/core/Lights/directionalLight.js';
import { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator.js';
import { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight.js';
import { Vector3 } from '@babylonjs/core/Maths/math.vector.js';
import { Color4,Color3 } from '@babylonjs/core/Maths/math.color.js';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder.js';
import { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial.js';
import { createRegionGate } from '../world/landmarks/createRegionGate.js';
await document.fonts.ready;
const engine=new Engine(document.getElementById('view'),true);engine.setHardwareScalingLevel(1/Math.min(devicePixelRatio,2));const scene=new Scene(engine);scene.clearColor=new Color4(.82,.91,.92,1);
const kind=new URLSearchParams(location.search).get('kind')||'village';const config={village:['Làng Bình Minh','#e4aa62',6.4],market:['Phố Chợ Phía Tây','#e69d64',9.2],lake:['Hồ Pha Lê','#65bfd0',9.2],beach:['Biển Bình Minh','#efd079',9.2]}[kind];
const camera=new ArcRotateCamera('camera',-Math.PI/2+.22,1.28,config[2]*3.6,new Vector3(0,3.5,0),scene);camera.attachControl(document.getElementById('view'),true);
new HemisphericLight('sun',new Vector3(-.4,1,-.5),scene).intensity=.6;
const sun=new DirectionalLight('key',new Vector3(.35,-1,.5),scene);sun.position.set(-20,30,-30);sun.intensity=.5;const shadows=new ShadowGenerator(1024,sun);shadows.useBlurExponentialShadowMap=true;shadows.blurKernel=16;
createRegionGate(scene,{position:{x:0,z:0},label:config[0],accent:config[1],halfSpan:config[2],shadows});
const grass=new StandardMaterial('grass',scene);grass.diffuseColor=Color3.FromHexString('#9ebb89');const ground=MeshBuilder.CreateGround('ground',{width:150,height:150},scene);ground.material=grass;ground.receiveShadows=true;
const roadMat=new StandardMaterial('road',scene);roadMat.diffuseColor=Color3.FromHexString('#c8c4b1');const road=MeshBuilder.CreateGround('road',{width:config[2]*2-2,height:150},scene);road.position.y=.02;road.material=roadMat;road.receiveShadows=true;
engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize());
