import {seaWaterColor,WATER_PALETTE} from '../../../shared/waterPalette.js';
import {createSeasideOcean} from '../world/landmarks/createSeasideOcean.js';
import {createRomanticLake} from '../world/landmarks/createRomanticLake.js';
import {DirectionalLight} from '@babylonjs/core/Lights/directionalLight.js';
import {ShadowGenerator} from '@babylonjs/core/Lights/Shadows/shadowGenerator.js';
import {LAKE_OUTLINE,LAKE_CENTER} from '../../../shared/lakeConfig.js';
import {Mesh} from '@babylonjs/core/Meshes/mesh.js';
import {MINIMAP_ROADS,MINIMAP_PARCELS} from '../world/minimapLayout.js';
import {VertexBuffer} from '@babylonjs/core/Buffers/buffer.js';
import {Engine} from '@babylonjs/core/Engines/engine.js';
import {Scene} from '@babylonjs/core/scene.js';
import {FreeCamera} from '@babylonjs/core/Cameras/freeCamera.js';
import {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight.js';
import {Vector3} from '@babylonjs/core/Maths/math.vector.js';
import {Color3,Color4} from '@babylonjs/core/Maths/math.color.js';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';
import {TransformNode} from '@babylonjs/core/Meshes/transformNode.js';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';
import {createWaterNetwork,createLandscapeWaterMaterial} from '../world/nature/createWaterNetwork.js';
import {createRiverStreamTexture,createStylizedWaterMaterial} from '../world/nature/StylizedWaterEngine.js';
import {sampleRiverSpline,RIVER_CONTROL_POINTS} from '../../../shared/riverLayout.js';
import {streamBanks} from '../../../shared/waterNetwork.js';
const engine=new Engine(document.getElementById('view'),true),scene=new Scene(engine);scene.useRightHandedSystem=true;scene.clearColor=new Color4(.77,.89,.94,1);
const view=new URLSearchParams(location.search).get('view'),close=view==='lake'||view==='confluence'||view==='sea',confluence=view==='confluence',sea=view==='sea';
const camera=new FreeCamera('camera',sea?new Vector3(430,230,370):confluence?new Vector3(80,160,-180):close?new Vector3(-540,145,-635):new Vector3(0,1550,-160),scene);camera.upVector=close?new Vector3(0,1,0):new Vector3(0,0,-1);camera.setTarget(sea?new Vector3(160,0,570):confluence?new Vector3(185,0,-20):close?new Vector3(-450,0,-455):new Vector3(0,0,-160));camera.minZ=close?1:10;camera.maxZ=4000;camera.attachControl(document.getElementById('view'),true);
new HemisphericLight('ambient',new Vector3(0,1,0),scene).intensity=.7;
const sun=new DirectionalLight('sun',new Vector3(.5,-1,.3),scene);sun.intensity=.65;sun.position.set(-550,160,-600);const shadows=new ShadowGenerator(1024,sun);shadows.useBlurExponentialShadowMap=true;shadows.blurKernel=16;
const mat=(name,color)=>{const m=new StandardMaterial(name,scene);m.diffuseColor=Color3.FromHexString(color);m.specularColor=Color3.Black();return m;};
const ground=MeshBuilder.CreateGround('grass',{width:1600,height:1800},scene);ground.material=mat('grass','#9ebb86');ground.receiveShadows=true;
const root=new TransformNode('network',scene),water=createLandscapeWaterMaterial(scene,root);
createWaterNetwork(scene,root,water,mat('sand','#e8d9ae'),shadows);
const samples=sampleRiverSpline(RIVER_CONTROL_POINTS,110),banks=streamBanks(samples);
const river=MeshBuilder.CreateRibbon('river',{pathArray:[banks[0],samples,banks[1]].map(bank=>bank.map(p=>new Vector3(p.x,.082,p.z))),sideOrientation:2},scene);river.material=water;
const positions=river.getVerticesData(VertexBuffer.PositionKind),normals=[],uvs=[],colors=[],n=samples.length;
for(let i=0;i<positions.length;i+=3){normals.push(0,1,0);uvs.push(positions[i]/48,positions[i+2]/48);const c=Color3.FromHexString(Math.floor((i/3)%(n*3)/n)===1?WATER_PALETTE.body:WATER_PALETTE.edge);const z=positions[i+2],ocean=seaWaterColor(positions[i],z),blend=Math.max(0,Math.min(1,(z-540)/100));colors.push(c.r+(ocean[0]-c.r)*blend,c.g+(ocean[1]-c.g)*blend,c.b+(ocean[2]-c.b)*blend,1);}
river.setVerticesData(VertexBuffer.NormalKind,normals);river.setVerticesData(VertexBuffer.UVKind,uvs);river.setVerticesData(VertexBuffer.ColorKind,colors);
createRomanticLake(scene,shadows);
createSeasideOcean(scene);
const roadMeshes=MINIMAP_ROADS.map(r=>{const m=MeshBuilder.CreateGround(r.id,{width:r.northSouth?r.width:r.length,height:r.northSouth?r.length:r.width},scene);m.position.set(r.x,.025,r.z);return m;});
Mesh.MergeMeshes(roadMeshes,true,true).material=mat('roads','#d6cfb4');
const lots=MINIMAP_PARCELS.map(p=>{const m=MeshBuilder.CreateGround(p.id,{width:p.width,height:p.depth},scene);m.position.set(p.x,.02,p.z);return m;});Mesh.MergeMeshes(lots,true,true).material=mat('lots','#b5c48f');
engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize());
