import {Engine} from '@babylonjs/core/Engines/engine.js';
import {Scene} from '@babylonjs/core/scene.js';
import {ArcRotateCamera} from '@babylonjs/core/Cameras/arcRotateCamera.js';
import {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight.js';
import {DirectionalLight} from '@babylonjs/core/Lights/directionalLight.js';
import {ShadowGenerator} from '@babylonjs/core/Lights/Shadows/shadowGenerator.js';
import '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent.js';
import {Vector3} from '@babylonjs/core/Maths/math.vector.js';
import {Color3,Color4} from '@babylonjs/core/Maths/math.color.js';
import {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder.js';
import {TransformNode} from '@babylonjs/core/Meshes/transformNode.js';
import {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial.js';
import {createWaterNetwork} from '../world/nature/createWaterNetwork.js';
import {createWaterfrontScenery} from '../world/nature/createWaterfrontScenery.js';
import {createMeadowTexture} from '../world/createStylizedTextures.js';
const engine=new Engine(document.getElementById('world'),true);engine.setHardwareScalingLevel(1/Math.min(devicePixelRatio,1.5));
const scene=new Scene(engine);scene.clearColor=new Color4(.77,.86,.9,1);
const camera=new ArcRotateCamera('camera',-1.25,.8,185,new Vector3(120,0,-540),scene);camera.attachControl(engine.getRenderingCanvas(),true);camera.minZ=.1;camera.maxZ=2200;
const fill=new HemisphericLight('sky',new Vector3(0,1,0),scene);fill.intensity=.62;fill.groundColor=new Color3(.23,.29,.18);
const sun=new DirectionalLight('sun',new Vector3(-.45,-1,.3),scene);sun.position.set(180,160,-620);sun.intensity=.72;
const shadows=new ShadowGenerator(2048,sun);shadows.usePercentageCloserFiltering=true;shadows.bias=.001;
const root=new TransformNode('landscape',scene),bank=new StandardMaterial('bank',scene);bank.diffuseColor=Color3.FromHexString('#b6bc8c');
createWaterNetwork(scene,root,null,bank,shadows);const scenery=createWaterfrontScenery(scene,root,shadows,{stream:false});
const ground=MeshBuilder.CreateGround('grass',{width:2000,height:2200},scene);const gm=new StandardMaterial('grass',scene);gm.diffuseColor=Color3.FromHexString('#8ba66c');gm.specularColor=Color3.Black();gm.diffuseTexture=createMeadowTexture(scene,512);gm.diffuseTexture.uScale=gm.diffuseTexture.vScale=100;ground.material=gm;ground.receiveShadows=true;
const rest=scenery.metadata.placements.find(p=>p.body==='lotus'&&p.kind==='rest');
const view=id=>{
 const p=id==='pine'?{x:120,z:-540,r:185,b:.8}:id==='lotus'?{x:-450,z:10,r:190,b:.8}:id==='river'?{x:-458,z:-330,r:110,b:.85}:{x:rest.x,z:rest.z,r:25,b:1.1};
 camera.setTarget(new Vector3(p.x,id==='close'?1.3:0,p.z));camera.radius=p.r;camera.beta=p.b;camera.alpha=id==='close'?rest.yaw-.7:-1.25;
 sun.position.set(p.x+100,160,p.z-90);
};
for(const button of document.querySelectorAll('[data-view]'))button.onclick=()=>view(button.dataset.view);
engine.runRenderLoop(()=>scene.render());window.addEventListener('resize',()=>engine.resize());
const timer=setInterval(()=>document.getElementById('metrics').textContent=new URLSearchParams(location.search).has('debug')?`${Math.round(engine.getFps())} FPS · ${scenery.metadata.placements.length} cụm cảnh vật`:'Phong cảnh ven hồ và sông',1000);
addEventListener('pagehide',()=>{clearInterval(timer);scene.dispose();engine.dispose();},{once:true});
