import {useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {HudIcon} from './icons3d/HudIcon.jsx';
import './GameFeedback.css';
export function GameConfirm({title,message,price,confirmLabel='Xác nhận',asset='hand',onConfirm,onCancel}){
 const root=useRef(null);
 useEffect(()=>{const previous=document.activeElement;root.current?.querySelector('[data-cancel]')?.focus();const keys=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onCancel();}if(e.key==='Tab'){const buttons=[...root.current.querySelectorAll('button')];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',keys,true);return()=>{document.removeEventListener('keydown',keys,true);if(previous?.isConnected)previous.focus();};},[onCancel]);
 return createPortal(<div className="game-confirm-overlay" onClick={e=>{if(e.target===e.currentTarget)onCancel();}}><section ref={root} className="game-confirm" role="alertdialog" aria-modal="true" aria-labelledby="game-confirm-title" aria-describedby="game-confirm-description"><div className="game-confirm-art"><HudIcon asset={asset} size={72}/></div><small>TRƯỚC KHI TIẾP TỤC</small><h2 id="game-confirm-title">{title}</h2><p id="game-confirm-description">{message}</p>{price!==undefined&&<div className="game-confirm-cost"><span>Giá</span><b><HudIcon asset="coin" size={25}/>{Number(price).toLocaleString('vi-VN')} xu</b></div>}<div className="game-confirm-actions"><button data-cancel onClick={onCancel}>Để sau</button><button className="game-confirm-primary" onClick={onConfirm}>{confirmLabel}</button></div></section></div>, document.body);
}
export function feedbackKind(message,offline=false){if(offline||/không đủ|chưa kết nối|chưa có kết nối|mất kết nối|thất bại|lỗi|không thể|cần kết nối|cần \d|thiếu /i.test(message))return 'warning';if(/thành công|đã mua|đã nhận|đã lưu|bạn nhận được|đã bán|chúc mừng|hoàn thành/i.test(message))return 'success';return 'info';}
export function GameToast({message,offline=false,onClose,kind}){
 const type=kind||feedbackKind(message,offline);const title=offline?'Đang kết nối lại':{success:'Thành công',warning:'Chú ý',info:'Thông báo'}[type];
 return <aside className={`game-toast game-toast-${type}`} role={type==='warning'?'alert':'status'} aria-live={type==='warning'?'assertive':'polite'}><div className="game-toast-icon"><img src={`/assets/hud/toast-v1/${type}.webp`} width="40" height="40" alt="" draggable="false"/></div><div><b>{title}</b><p>{offline?'Mất kết nối. Đang kết nối lại, bạn chờ một chút nhé.':message}</p></div>{!offline&&<button aria-label="Đóng thông báo" onClick={onClose}>×</button>}</aside>;
}
