import { useEffect, useState } from 'react';
import { firstLandPurchasePrice, STARTER_LAND_DISCOUNT } from '../../shared/landConfig.js';
import { LAND_EXPANSION_CONFIG } from '../../shared/landExpansionConfig.js';
import {HudIcon} from './icons3d/HudIcon.jsx';
import './LandMarket.css';
const xu=value=>Number(value||0).toLocaleString('vi-VN');
export function LandMarket({ lots, focusFarmId, playerId, ownsLand, coins, pending, onBuy, onVisit }) {
 const [village,setVillage]=useState(''),[affordableOnly,setAffordableOnly]=useState(false),[visibleCount,setVisibleCount]=useState(36),[selected,setSelected]=useState(focusFarmId||null),[tab,setTab]=useState(ownsLand?'rights':'market');
 useEffect(()=>{setSelected(focusFarmId||null);if(focusFarmId)setTab('market');},[focusFarmId]);
 useEffect(()=>{if(ownsLand&&!focusFarmId)setTab('rights');},[ownsLand,focusFarmId]);
 const current=lots.find(lot=>lot.farmId===selected),owned=lots.find(lot=>lot.ownerId===playerId),focused=Boolean(selected);
 const priceToPay=lot=>ownsLand?lot.price:firstLandPurchasePrice(lot.price);
 const listed=lots.filter(lot=>(!village||lot.villageId===village)&&(!affordableOnly||(lot.available&&priceToPay(lot)<=coins))).sort((a,b)=>Number(b.available)-Number(a.available)||priceToPay(a)-priceToPay(b));
 const tiles=LAND_EXPANSION_CONFIG.columns*LAND_EXPANSION_CONFIG.rows,start=LAND_EXPANSION_CONFIG.initialTiles.length;
 return <div className="land-market"><div className="land-wallet"><HudIcon asset="land" size={45}/><div><b>Một mảnh đất, một nông trại riêng</b><small>Chọn nơi bắt đầu cuộc sống làm nông</small></div><span><HudIcon asset="coin" size={25}/><b>{xu(coins)}</b><small>xu</small></span></div>
 <nav className="land-tabs" aria-label="Đất đai"><button aria-pressed={tab==='market'} onClick={()=>setTab('market')}>Chọn mua đất</button><button aria-pressed={tab==='rights'} onClick={()=>setTab('rights')}>Quyền sử dụng đất</button></nav>
 {tab==='rights'?<section className="land-rights"><div className="land-deed"><HudIcon asset="land" size={70}/><small>NÔNG TRẠI CỦA BẠN</small><h3>{ownsLand?(owned?`${owned.villageName} · Lô ${owned.lot}`:'Đất đã sở hữu'):'Chưa có quyền sử dụng đất'}</h3><p>{ownsLand?'Quyền sử dụng gắn với tài khoản của bạn trong trò chơi.':'Mua một lô đất để xây dựng nông trại của riêng mình.'}</p>{owned&&<dl><div><dt>Mã lô</dt><dd>{owned.farmId}</dd></div><div><dt>Chủ đất</dt><dd>{owned.userName||'Bạn'}</dd></div><div><dt>Trạng thái</dt><dd>Đã sở hữu</dd></div></dl>}</div><div className="land-rights-grid">{[['seeds','Trồng trọt','Gieo hạt, tưới nước và thu hoạch trên các ô đã mở.'],['gate','Phát triển nông trại',`Nhận nhà nhỏ và ${start} ô khởi đầu. Khai hoang dần đến ${tiles} ô.`],['land','Một tài khoản, một lô','Hiện mỗi người chơi được sở hữu một lô đất.'],['hand','Quyền của chủ đất','Chủ đất chọn và khai hoang các ô để mở rộng diện tích trồng.']].map(([icon,title,text])=><article key={title}><HudIcon asset={icon} size={34}/><div><b>{title}</b><p>{text}</p></div></article>)}</div>{owned?<button className="land-primary" onClick={()=>onVisit(owned)}>Đến cổng làng của bạn</button>:!ownsLand&&<button className="land-primary" onClick={()=>setTab('market')}>Chọn lô đất đầu tiên</button>}</section>:<>
 {focused&&!focusFarmId&&<button className="land-more" onClick={()=>setSelected(null)}>‹ Quay lại các lô đất</button>}
 <div className="land-intro"><HudIcon asset="gate" size={37}/><div><b>Nhận nhà nhỏ và {start} ô trồng khởi đầu</b><p>Mỗi lô có {tiles} ô. Gần trung tâm thị trấn đắt hơn; lô xa rẻ hơn.{STARTER_LAND_DISCOUNT>0&&` Mua lần đầu giảm tối đa ${xu(STARTER_LAND_DISCOUNT)} xu.`}</p></div></div>
 {!focused&&<div className="land-filters"><label>Làng<select value={village} onChange={e=>{setVillage(e.target.value);setSelected(null);setVisibleCount(36);}}><option value="">Tất cả làng</option>{[...new Map(lots.map(l=>[l.villageId,l.villageName]))].map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><button aria-pressed={affordableOnly} onClick={()=>{setAffordableOnly(!affordableOnly);setVisibleCount(36);}}>{affordableOnly?'Chỉ lô đủ xu':'Lọc lô đủ xu'}</button><small>{listed.length} lô · giá thấp trước</small></div>}
 {current&&<section className="land-confirm"><div className="land-confirm-heading"><HudIcon asset="land" size={46}/><div><small>LÔ ĐẤT ĐÃ CHỌN</small><b>{current.villageName} · Lô {current.lot}</b></div><span>{current.available?'Đang bán':current.ownerId===playerId?'Của bạn':current.userName?'Đã có chủ':'Đang giao dịch'}</span></div><p>{current.distance} m tới trung tâm thị trấn · {tiles} ô đất · {start} ô mở sẵn</p><dl className="land-price-summary"><div><dt>Giá niêm yết</dt><dd>{xu(current.price)} xu</dd></div><div><dt>Bạn trả</dt><dd>{xu(priceToPay(current))} xu</dd></div><div><dt>Số dư sau mua</dt><dd className={coins<priceToPay(current)?'is-short':''}>{xu(coins-priceToPay(current))} xu</dd></div></dl>{!current.available&&<p>{current.userName?`Chủ sở hữu: ${current.userName}`:'Lô đất đang được xử lý.'}</p>}{ownsLand&&current.available&&<p>Bạn đã có đất. Hiện chưa thể mua thêm lô thứ hai.</p>}<div className="land-confirm-actions"><button onClick={()=>onVisit(current)}>Đến cổng làng xem đất</button>{current.available&&!ownsLand&&<button className="land-primary" disabled={pending||coins<priceToPay(current)} onClick={()=>onBuy(current)}>{pending?'Đang xác nhận…':coins<priceToPay(current)?`Thiếu ${xu(priceToPay(current)-coins)} xu`:`Mua lô đất · ${xu(priceToPay(current))} xu`}</button>}</div><small>Mua thành công để nhận quyền sử dụng lô đất này.</small></section>}
 {!lots.length&&<p role="status">Đang tìm các lô đất…</p>}{focused&&!current&&lots.length>0&&<p role="status">Lô đất đang cập nhật. Hãy chọn lại sau nhé.</p>}
 {!focused&&<div className="land-lots">{!listed.length&&lots.length>0&&<div className="land-empty"><HudIcon asset="land" size={50}/><b>Chưa có lô phù hợp</b><p>Đổi làng hoặc tắt bộ lọc đủ xu để xem thêm.</p></div>}{listed.slice(0,visibleCount).map(lot=><button key={lot.farmId} className="land-lot" aria-pressed={selected===lot.farmId} onClick={()=>setSelected(lot.farmId)}><div className="land-lot-art"><HudIcon asset="land" size={62}/><span>{lot.available?'Đang bán':lot.ownerId===playerId?'Của bạn':'Đã có chủ'}</span></div><b>{lot.villageName} · Lô {lot.lot}</b><small>{lot.distance} m tới trung tâm</small><em><HudIcon asset="coin" size={20}/>{xu(priceToPay(lot))} xu</em></button>)}{listed.length>visibleCount&&<button className="land-more" onClick={()=>setVisibleCount(n=>n+36)}>Xem thêm · {Math.min(visibleCount,listed.length)}/{listed.length} lô</button>}</div>}
 </>}</div>;
}
